/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package goomble;

import org.junit.jupiter.api.Test;

import goomble.GoombleSimulation;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        GoombleSimulation classUnderTest = new GoombleSimulation(0);
    }
}
